name: succ
description: A calm plant simulator.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
    #window_size:
    #git:
        #url: git://github.com/google/flutter-desktop-embedding.git
          #path: plugins/window_size
  card_swiper: 
  curved_navigation_bar: 
  path_provider: 
  simple_animations: 
  auto_size_text: ^3.0.0-nullsafety.0
  build_web_compilers: ^4.0.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/

